apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 172.31.33.20
    path: "/mnt/nfs_share"

